```mermaid
classDiagram
    class DormRegistrationRequest
    class Student
    class DormRegistrationPeriod
    DormRegistrationRequest "1" --> "1" Student
    DormRegistrationRequest "1" --> "1" DormRegistrationPeriod
```
